corrections have been made to the project
nkokina/Diplom_Prestashop_Kokina_QA19 pull request #2
Opened 2022-09-15 07:51 UTC by nkokina

Я сделала регистрацию в BaseTest как вы мне и сказали только через BeforeMetod, так как BeforeSuite идет даже раньше BeforeClass, т.е. до запуска драйвера и открытия страницы.

2022-09-15 19:05 UTC, voropa commented
> Я сделала регистрацию в BaseTest как вы мне и сказали только через BeforeMetod, так как BeforeSuite идет даже раньше BeforeClass, т.е. до запуска драйвера и открытия страницы.

Дело в том, что это очень излишне  получается и очень замедляет ваши тесты. У вас перед выполнением каждого тестового метода будет создаваться новый пользователь. Лучше добавьте создание нового пользователя только в тот тестовый класс, где это необходимо, насколько я помню, это в тестах на checkout. Для остальных тестов же можно использоваать одного и того же польщователя по умолчанию. А тестах на checkout создавайте нового в beforeClass

2022-09-15 19:07 UTC, voropa requested changes

2022-09-15 19:07 UTC, voropa commented on src/test/java/tests/SearchTest.java
> +        Assert.assertFalse(searchPage.getErrorMessageDisplayed().isEmpty(), "Field are empty");
Проверяйте сам текст сообщение, а не просто его наличие и то, что он не пустой

2022-09-15 19:46 UTC, nkokina commented on src/test/java/tests/SearchTest.java
> +        Assert.assertFalse(searchPage.getErrorMessageDisplayed().isEmpty(), "Field are empty");
Дело в том что там раз в сутки сбрасывают все пароли.

2022-09-15 20:13 UTC, voropa commented on src/test/java/tests/SearchTest.java
> +        Assert.assertFalse(searchPage.getErrorMessageDisplayed().isEmpty(), "Field are empty");
Понял, ну тогда хотя бы в beforeClass переместите этот код с созданием пользователя, чтобы у нас он создавался один раз перед каждым тестовым классом, а не перед каждым отдельным тестом.

2022-09-17 04:30 UTC, nkokina commented on src/test/java/tests/SearchTest.java
> +        Assert.assertFalse(searchPage.getErrorMessageDisplayed().isEmpty(), "Field are empty");
Т.е. в BaseTest в BeforeClass добавить navigate+userRegistration, так как если я добавлю только userRegistration, он не будет работать так как сайт не будет открыт, или в каждом тестовом классе создать BeforeClass?

2022-09-18 19:16 UTC, voropa commented on src/test/java/tests/SearchTest.java
> +        Assert.assertFalse(searchPage.getErrorMessageDisplayed().isEmpty(), "Field are empty");
У вас в BaseTest классе есть BeforeClass метод, в котором конфигурируется драйвер и создаются обьекты классов страниц. Так вот туда, после всех этих действий пометсите код, который будет заходить на сайт и создавать нового польщователя

2022-09-18 19:21 UTC, voropa requested changes

2022-09-18 19:21 UTC, voropa commented on src/test/java/tests/ItemDetailsTest.java
> +        loginPage.clickLoginButton();
А вот эти 2 действия: 
loginPage.clickLoginButton();
loginPage.login(userEmail, userPassword);

У вас повторяются в начале каждого теста, так что их лучше вынести в bbeforeMethod, чтобы не дублировать в каждом тесте

2022-09-18 19:21 UTC, voropa commented on src/test/java/page/MyAccountPage.java
> +    public void waitForElementDisplayed() {
Слишком абстрактное название метода, добавьте конкретики: какого именно элемента ждет

2022-09-19 11:28 UTC, voropa approved these changes

2022-09-19 12:01 UTC, merged